import Head from 'next/head';
import Layout from '../components/Layout';
export default function Home() {
  return (
    <>
      <Head>
        <title>For When?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout />

        <div className="w-auto h-auto bg-primary-blue">
          <h1 className="text-h900 text-primary-yellow">Hello world!</h1>
        </div>
        <div className="w-28px h-10px bg-primary-grayDark st"> aaaa</div>
      </main>
    </>
  );
}
