import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import NextButton from '../components/NextButton';
import SearchBar from '../components/SearchBar';
import NextArrow from '../components/NextArrow';



export default function Home() {
  return (
    <>
      <Head>
        <title>For When?</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='w-auto h-auto bg-primary-blue'>
        <h1 className="text-h900 text-primary-yellow">
      Hello world!!!!!!!
  </h1>  
</div>
<div className='w-28px h-10px bg-primary-grayDark st'> aaaa</div>
       <div>
       <NextButton/>
       <SearchBar/>
       <NextArrow/>
       </div>
      </main>
    </>
  );
}
